CREATE TABLE IF NOT EXISTS room (
id UUID PRIMARY KEY, 
name VARCHAR NOT NULL UNIQUE, 
description VARCHAR NULL, 
logo_url VARCHAR NULL, 
website VARCHAR NULL, 
is_active BOOLEAN NOT NULL DEFAULT TRUE, 
created_at TIMESTAMP NOT NULL DEFAULT NOW(), 
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_room_name ON room (name); 