# Docker Compose configuration for Fonds Relations project

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "ls -la /app && cat /app/start.sh && /app/start.sh"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - PROJECT_NAME=FondsRelations
      - SECRET_KEY=your-secret-key-here
      - API_V1_STR=/api/v1
      - SERVER_HOST=http://localhost:8000
      - BACKEND_CORS_ORIGINS=["http://localhost:8000"]
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SMTP_TLS=True
      - SMTP_PORT=587
      - SMTP_HOST=
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAILS_FROM_EMAIL=test@example.com
      - EMAILS_FROM_NAME=Test
      - EMAIL_RESET_TOKEN_EXPIRE_HOURS=48
      - EMAIL_TEMPLATES_DIR=/app/app/email-templates/build
      - EMAILS_ENABLED=False
      - USERS_OPEN_REGISTRATION=True
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/migrations:/app/migrations
      - ./backend/tests:/app/tests
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/wait_for_services.py:/app/wait_for_services.py
      - ./backend/start.sh:/app/start.sh
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  elasticsearch_data: 