FROM python:3.9-slim

WORKDIR /app

# Устанавливаем зависимости для сборки
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем код приложения и тесты
COPY . .

# Запускаем тесты
CMD ["pytest", "-v", "--cov=app", "--cov-report=term-missing", "tests/"] 