"""Add health_notes field to Player model

Revision ID: add_health_notes_field
Revises: 87a654f78d34
Create Date: 2025-03-04 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_health_notes_field'
down_revision = '87a654f78d34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Применяет изменения к базе данных при миграции вперед."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('health_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает изменения в базе данных при миграции назад."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'health_notes')
    # ### end Alembic commands ### 