name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/fonds-relations
          git pull origin main
          cd backend
          cp .env.example .env
          # Обновляем переменные окружения из секретов
          sed -i "s/your-secret-key-here/${{ secrets.APP_SECRET_KEY }}/g" .env
          sed -i "s/your-email@gmail.com/${{ secrets.SMTP_USER }}/g" .env
          sed -i "s/your-app-specific-password/${{ secrets.SMTP_PASSWORD }}/g" .env
          # Перезапускаем контейнеры
          docker-compose down
          docker-compose up -d --build 