name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            # Проверка наличия Docker и Docker Compose
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi
            
            if ! command -v docker-compose &> /dev/null; then
              curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            fi
            
            # Создание рабочей директории если её нет
            mkdir -p /var/www/fonds-relations
            
            # Очистка и подготовка директории
            cd /var/www/fonds-relations
            
            # Клонирование репозитория если его нет
            if [ ! -d ".git" ]; then
              git clone https://github.com/MrNightOmsk/fonds-relations.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi
            
            # Создание .env файла
            echo "${{ secrets.ENV_FILE }}" > backend/.env
            
            # Остановка и удаление старых контейнеров
            docker-compose down
            
            # Сборка и запуск новых контейнеров
            docker-compose up -d --build
            
            # Очистка неиспользуемых образов
            docker image prune -f
            
            # Проверка статуса контейнеров
            docker-compose ps
          ' 