name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: unnecessary
          config: |
            Host 45.91.200.192
              StrictHostKeyChecking no
          
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@45.91.200.192 "cd /var/www/fonds_relations && \
          git reset --hard && \
          git clean -fd && \
          git pull && \
          rm -rf frontend-old && \
          mv frontend frontend-old && \
          yes | npx create-next-app@latest frontend --typescript --tailwind --eslint --app --src-dir --import-alias '@/*' --no-git && \
          cd frontend && \
          rm -rf src/app/* src/components src/lib src/hooks && \
          mkdir -p src/components src/lib src/hooks && \
          cp -r ../frontend-old/src/app/* src/app/ && \
          cp -r ../frontend-old/src/components/* src/components/ && \
          cp -r ../frontend-old/src/lib/* src/lib/ && \
          cp -r ../frontend-old/src/hooks/* src/hooks/ && \
          cp ../frontend-old/tailwind.config.js . && \
          cp ../frontend-old/postcss.config.js . && \
          echo $'@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --foreground-rgb: 0, 0, 0;\n  --background-rgb: 255, 255, 255;\n}\n\nbody {\n  color: rgb(var(--foreground-rgb));\n  background: rgb(var(--background-rgb));\n}' > src/app/globals.css && \
          npm install && \
          npm install @radix-ui/react-dialog @radix-ui/react-dropdown-menu @radix-ui/react-toast @tanstack/react-table class-variance-authority clsx lucide-react tailwind-merge && \
          npm run build && \
          cd ../backend && \
          source venv/bin/activate && \
          pip install -r ../requirements.txt && \
          sudo systemctl restart fonds-backend && \
          sudo systemctl restart fonds-frontend" 